/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-07 10:01:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.triby.member.model.vo.Member;

public final class myLikeTriby_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/member/../member/myPageHeader.jsp", Long.valueOf(1570439778728L));
    _jspx_dependants.put("/views/member/../member/../common/header.jsp", Long.valueOf(1570439993729L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.triby.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");

   String contextPath = request.getContextPath();
   Member loginUser = (Member)session.getAttribute("loginUser");
   String msg = (String)session.getAttribute("joinSuccessMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/triby_myPage.css\">\r\n");
      out.write("    <title>TRIBY</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("      var msg = \"");
      out.print(msg);
      out.write("\";\r\n");
      out.write("      if(msg != \"null\") {\r\n");
      out.write("         alert(msg);\r\n");
      out.write("         ");
session.removeAttribute("joinSuccessMsg");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("   })\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("    a, a:hover{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("    a:link, a:visited, a:hover{\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("    header{\r\n");
      out.write("        width:100%;\r\n");
      out.write("    }   \r\n");
      out.write("    #header{\r\n");
      out.write("        width:50%;\r\n");
      out.write("        height: 60px;\r\n");
      out.write("        margin:0 auto;\r\n");
      out.write("        border: 0px solid black;\r\n");
      out.write("    }\r\n");
      out.write("    #logo_bar{\r\n");
      out.write("        width:20%;\r\n");
      out.write("        height:100%;\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("    #logo{\r\n");
      out.write("        width:90%;\r\n");
      out.write("        height:100%;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("    #search_bar{\r\n");
      out.write("        width:45%;\r\n");
      out.write("        height:100%;\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("   \t#search_form{\r\n");
      out.write("    \twidth:100%;\r\n");
      out.write("    \theight:100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #search{\r\n");
      out.write("        border:0px solid black;\r\n");
      out.write("        width:92.5%;\r\n");
      out.write("        height:90%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #right{\r\n");
      out.write("        float: right;\r\n");
      out.write("        border:0px solid black;\r\n");
      out.write("        /* text-align: center; */\r\n");
      out.write("        width:34.5%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        top:25px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("    #right_menu{\r\n");
      out.write("        height:100%;\r\n");
      out.write("        line-height: 50px;\r\n");
      out.write("    }\r\n");
      out.write("    #login_right_menu{\r\n");
      out.write("       border : 0px solid black;\r\n");
      out.write("       height:20%;\r\n");
      out.write("        line-height:50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #signup1,#login1{\r\n");
      out.write("        min-height: 1px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #signup_background,#login_background,#center_background{\r\n");
      out.write("        display: inline;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    #signup_text,#login_text,#center_text{\r\n");
      out.write("        text-decoration:none;\r\n");
      out.write("        max-width: 85px;\r\n");
      out.write("        height: 14px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        font-style: normal;\r\n");
      out.write("        font-stretch: normal;\r\n");
      out.write("        line-height: 1;\r\n");
      out.write("        letter-spacing: normal;\r\n");
      out.write("        text-align: right;\r\n");
      out.write("        color: rgb(0, 0, 0);\r\n");
      out.write("    }\r\n");
      out.write("    #boundary{\r\n");
      out.write("        width: 1px;\r\n");
      out.write("        height: 10px;\r\n");
      out.write("        background-color: rgb(221, 221, 221);\r\n");
      out.write("        margin-left: 14px;\r\n");
      out.write("        margin-right: 14px;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("    }\r\n");
      out.write("    #arrow{\r\n");
      out.write("        margin-left: 4px;\r\n");
      out.write("        width: 18px;\r\n");
      out.write("        height: 18px;\r\n");
      out.write("        transform: rotate(90deg);\r\n");
      out.write("        vertical-align: text-bottom;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    #center_category{\r\n");
      out.write("        width: 124px;\r\n");
      out.write("        background-color: rgb(255, 255, 255);\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        z-index: 200;\r\n");
      out.write("        left:0px;\r\n");
      out.write("        top: 30px;\r\n");
      out.write("        border-width: 1px;\r\n");
      out.write("        border-style: solid;\r\n");
      out.write("        border-color: rgb(238, 238, 238);\r\n");
      out.write("        border-image: initial;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    #notice_text, #question_text,#signHost_text{\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        line-height: 24px;\r\n");
      out.write("        margin: 3px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("#loginUser1 {\r\n");
      out.write("   height: 18px;\r\n");
      out.write("   width: 45px;\r\n");
      out.write("   display: inline;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginUser2 {\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("   max-width: 85px;\r\n");
      out.write("   height: 14px;\r\n");
      out.write("   font-size: 14px;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   font-style: normal;\r\n");
      out.write("   font-stretch: normal;\r\n");
      out.write("   line-height: 1;\r\n");
      out.write("   letter-spacing: normal;\r\n");
      out.write("   text-align: right;\r\n");
      out.write("   color: rgb(0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginUser_category {\r\n");
      out.write("   width: 124px;\r\n");
      out.write("   background-color: rgb(255, 255, 255);\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   z-index: 200;\r\n");
      out.write("   left: 58%;\r\n");
      out.write("   top: 7.5%;\r\n");
      out.write("   border-width: 1px;\r\n");
      out.write("   border-style: solid;\r\n");
      out.write("   border-color: rgb(238, 238, 238);\r\n");
      out.write("   border-image: initial;\r\n");
      out.write("   border-radius: 5px;\r\n");
      out.write("   padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("    #like2, #buy2, #coupon2, #mypage2, #logout2 {\r\n");
      out.write("     font-size: 12px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      line-height: 24px;\r\n");
      out.write("      margin: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- 헤더 부분 화면의   //  100%를 큰 틀로 잡고 -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <!-- 헤더 큰틀 이 안에서만 작업  //그 100% 중에 50%를 다시 중간 틀로 잡고 작업 -->\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <!-- 헤더 중에서 로고 들어갈 1번 구역 -->\r\n");
      out.write("            <div id=\"logo_bar\">\r\n");
      out.write("                <div id=\"logo\">\r\n");
      out.write("                    <a href=\"#\"><img src=\"");
      out.print(contextPath);
      out.write("/resources/images/로고.png\" height=\"60%;\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 헤더 중에서 서치바 들어갈 2번 구역 -->\r\n");
      out.write("            <div id=\"search_bar\">\r\n");
      out.write("            \t<form method=\"get\" id=\"search_form\">\r\n");
      out.write("                \t<input type=\"text\" id=\"search\" name=\"search\" placeholder=\"새로운 취미를 경험해보세요!\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 헤더 중에서 오른쪽 버튼 들어갈 3번 구역 -->\r\n");
      out.write("            <div id=\"right\">\r\n");
      out.write("            ");
if(loginUser == null) { 
      out.write("\r\n");
      out.write("                <div id=\"right_menu\">\r\n");
      out.write("                    <a id=\"signup_a\" href=\"");
      out.print(request.getContextPath());
      out.write("/form.me\">\r\n");
      out.write("                        <div id=\"signup_background\">\r\n");
      out.write("                            <span id=\"signup_text\">회원가입</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <span id=\"boundary\"></span>\r\n");
      out.write("                    <a id=\"login_a\" href=\"");
      out.print(request.getContextPath());
      out.write("/loginpg.me\">\r\n");
      out.write("                        <div id=\"login_background\">\r\n");
      out.write("                            <span id=\"login_text\">로그인</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <span id=\"boundary\"></span>\r\n");
      out.write("                    <div id=\"center_background\">\r\n");
      out.write("                            <span id=\"center_text\">\r\n");
      out.write("                                   고객센터\r\n");
      out.write("                                <img src= \"");
      out.print(contextPath);
      out.write("/resources/images/캡처.PNG\" id=\"arrow\">\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <div id=\"center_category\" style=\"display: none\">\r\n");
      out.write("                                <a id=\"notice_a\" href=#>\r\n");
      out.write("                                    <div id=\"notice_text\">공지사항</div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a id=\"question_a\" href=#>\r\n");
      out.write("                                    <div id=\"question_text\">자주 묻는 질문</div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a id=\"signHost_a\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminSignup.ho\">\r\n");
      out.write("                                    <div id=\"signHost_text\">호스트 가입</div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    ");
}else{ 
      out.write("\r\n");
      out.write("                    <div id = \"login_right\">\r\n");
      out.write("                    <div id =\"login_right_menu\" >\r\n");
      out.write("            \r\n");
      out.write("               <div id=\"loginUser1\">\r\n");
      out.write("                  <span id=\"loginUser2\"> ");
      out.print(loginUser.getUser_name());
      out.write("트리버님 <img src=\"");
      out.print(contextPath);
      out.write("/resources/images/캡처.PNG\" id=\"arrow\">\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <div id=\"loginUser_category\" style=\"display:none\">\r\n");
      out.write("                     <a id=\"like1\" href=\"myLike/triby.me\">\r\n");
      out.write("                        <div id=\"like2\">좋아요</div>\r\n");
      out.write("                     </a> <a id=\"buy1\" href=\"myLike/triby.me\">\r\n");
      out.write("                        <div id=\"buy2\">구매목록</div>\r\n");
      out.write("                     </a> <a id=\"coupon1\" href=#>\r\n");
      out.write("                        <div id=\"coupon2\">쿠폰</div>\r\n");
      out.write("                     </a> <a id=\"mypage1\" href=#>\r\n");
      out.write("                        <div id=\"mypage2\">마이 페이지</div>\r\n");
      out.write("                     </a> <a id=\"logout1\" href=#>\r\n");
      out.write("                        <div id=\"logout2\" onclick=\"logout();\">로그아웃</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("            \r\n");
      out.write("            <span id=\"boundary\"></span>\r\n");
      out.write("         <div id=\"center_background\">\r\n");
      out.write("                <span id=\"center_text\">\r\n");
      out.write("                                고객센터\r\n");
      out.write("                 <img src= \"");
      out.print(contextPath);
      out.write("/resources/images/캡처.PNG\" id=\"arrow\">\r\n");
      out.write("                   </span>\r\n");
      out.write("                    <div id=\"center_category\" style=\"display: none\">\r\n");
      out.write("                                <a id=\"notice_a\" href=#>\r\n");
      out.write("                                    <div id=\"notice_text\">공지사항</div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a id=\"question_a\" href=#>\r\n");
      out.write("                                    <div id=\"question_text\">자주 묻는 질문</div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a id=\"signHost_a\" href=\"");
      out.print(request.getContextPath());
      out.write("/signup.ho\">\r\n");
      out.write("                                    <div id=\"signHost_text\">호스트 가입</div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("          \r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("      </div>\r\n");
      out.write("                        \r\n");
      out.write("    </header>\r\n");
      out.write("    <hr>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   \r\n");
      out.write("      $(function () {\r\n");
      out.write("          $(\"#center_text\").on(\"click\", function () {\r\n");
      out.write("           $(\"#center_category\").toggle(1);\r\n");
      out.write("        $(\"#loginUser_category\").hide(1);\r\n");
      out.write("            });\r\n");
      out.write("      });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   $(function() {\r\n");
      out.write("      $(\"#loginUser2\").on(\"click\", function() {\r\n");
      out.write("         $(\"#loginUser_category\").toggle(1);\r\n");
      out.write("         $(\"#center_category\").hide(1);\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("   function logout(){\r\n");
      out.write("       location.href=\"");
      out.print(contextPath );
      out.write("/logout.me\";\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/triby_myPage.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"outer\">\r\n");
      out.write("    <div class=\"profileWrap\">\r\n");
      out.write("        <div class=\"profile\">\r\n");
      out.write("            <input type=\"file\" accept=\".jpg, .jpeg, .png\">\r\n");
      out.write("            <div class=\"pic\">\r\n");
      out.write("                <img src=\"city1.png\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"userinfo\">\r\n");
      out.write("                <div class=\"nickname\">트리비대원</div>\r\n");
      out.write("                <div class=\"edit\">변경</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"coupon\">\r\n");
      out.write("            <h2>쿠폰</h3>\r\n");
      out.write("            <div class=\"count\">3개</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <div class=\"infoWrap\">\r\n");
      out.write("        <div class=\"navWrap\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <a href=\"#\" class=\"nav tagactive\">좋아요</a>\r\n");
      out.write("                <a href=\"#\" class=\"nav\">내 트리비</a>\r\n");
      out.write("                <a href=\"#\" class=\"nav\">쿠폰</a>\r\n");
      out.write("                <a href=\"#\" class=\"nav\">프로필 수정</a>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
